[package]
name = "net_traits"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
name = "net_traits"
path = "lib.rs"

[dependencies]
hyper = "0.9.9"
hyper_serde = "0.1.4"
serde = "0.8"
serde_derive = "0.8"
